spring:
  application:
    name: transcoder-service

datasource:
  url: jdbc:postgresql://localhost:5432/nginx_spring
  username: root
  password: root
  driver-class-name: org.postgresql.Driver
  hikari:
    maximum-pool-size: 10
    minimum-idle: 5
    idle-timeout: 30000
    pool-name: HikariCP
    max-lifetime: 2000000
    connection-timeout: 30000
