spring:
  application:
    name: nginx-spring
  
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/nginx_spring
    username: postgres
    password: postgres
    pool:
      enable: true

# Application file paths. Override with environment variables if desired.
file:
  video-dir: D:/Code/git/nginx-spring/videos

# RabbitMQ configuration

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
  queue: 
    name: video_transcode_queue
  exchange: 
    name: video_transcode_exchange
  routing: 
    key: video.transcode.key
